### ISSUE TITLE
Support data sets with > 1600 columns

### ISSUE THREAD

**Issue by robertzk** [robertzk/cachemeifyoucan#14]
Postgres has a [1600 column limit](http://stackoverflow.com/a/12612255/2540303). This is too low for many applications. Potential solutions include

(1) Use a 2-column setup, primary key and raw json in the other. In this scenario we may almost as well go with Mongo.
(2) Shard the postgres table if it gets too big. Seems messy and unwieldy, but then again we md5 hash column names.
(3) Try a totally different db driver and hope the integrity of our data is preserved, e.g., monetDB

**Comment by peterhurford** [comment]
Have you made a decision on sharding vs. MonetDB?

**Comment by kirillseva** [comment]
MonetDB works almost out-of-the-box
Need to modify berdie to correctly choose the driver based on the name

**Comment by robertzk** [comment]
We have sharding so this is closed.
