### ISSUE TITLE
batchman integration

### ISSUE THREAD

**Issue by FeiYeYe** [robertzk/cachemeifyoucan#55]
Error in print_batching_message(run_length, size, batchman.verbose) : 
  object 'batch_size' not found
Calls: run ... body_fn -> splitting_strategy -> print_batching_message

**Comment by FeiYeYe** [comment]
@peterhurford any ideas?

**Comment by peterhurford** [comment]
Can you post the code you ran to get the error message?

**Comment by FeiYeYe** [comment]
https://github.com/avantcredit/avant-analytics/blob/survival_classifier_86221272/models/dev/survival/1.0.0/1.0.0.R#L11

**Comment by FeiYeYe** [comment]
part of the import has finished, it errored out when batching source I guess

**Comment by robertzk** [comment]
Reinstall [redacted] pkg

**Comment by robertzk** [comment]
@FeiYeYe Still issues with this or did that work?

**Comment by FeiYeYe** [comment]
@robertzk didn't work, same error, 

if i switched to the previous version and run [redacted] data source, it hangs
