### ISSUE TITLE
Logical inputs are converted to character in the DB layer

### ISSUE THREAD

**Issue by robertzk** [robertzk/cachemeifyoucan#69]

**Comment by kirillseva** [comment]
I thought this is intentional?

**Comment by robertzk** [comment]
``` r
Browse[3]> fn <- function(id) { data.frame(id = id, foo = rep(TRUE, seq_along(id))) }
Browse[3]> cfn <- cache(fn, "id")
Browse[3]> cfn(1)
  id  foo
1  1 TRUE
[1] 1 2
Browse[3]> class(cfn(1)[[2]])
[1] "character"
```

**Comment by rylandely** [comment]
Isn't that solved by the old
`"Convert logical to factor"        = list( column_transformation(factor), is.logical ) `
mungebit?

**Comment by rylandely** [comment]
Errrr, maybe not

**Comment by robertzk** [comment]
I knew it was happening to factor variables, but I don't think it's intentional for logical variables.

**Comment by kirillseva** [comment]
https://github.com/robertzk/cachemeifyoucan/blob/master/R/db.R#L278-L280

**Comment by kirillseva** [comment]
@robertzk should logical be removed from that map?

**Comment by robertzk** [comment]
And changed here: https://github.com/robertzk/cachemeifyoucan/blob/master/R/db.R#L347

**Comment by kirillseva** [comment]
That's just duplication (not DRY!!), but not an overwrite. That thing triggers when you want to add a new column to an existing table
