### ISSUE TITLE
Add super debug mode

### ISSUE THREAD

**Issue by robertzk** [robertzk/cachemeifyoucan#94]
That lists a large amount of helpful metadata while running a cached function.
1. What primary keys are cached versus uncached, and the size.
2. The names of the tables being consulted, including shards.
3. The dimensions of those tables.
4. Additional warning flags on any unmet expectations (like different row-size shards or 
5. Etc?

**Comment by kirillseva** [comment]
:santa:

**Comment by robertzk** [comment]
Too tired of adding stray `debug()` by hand. >_<

**Comment by kirillseva** [comment]
https://github.com/robertzk/cachemeifyoucan/pull/97 addresses this issue
