### ISSUE TITLE
Can't run tests locally

### ISSUE THREAD

**Issue by peterhurford** [robertzk/cachemeifyoucan#95]
It continues to insist that I "Cannot run tests until you create a database named ‘travis’ for user ‘postgres’" even after I do so.

**Comment by peterhurford** [comment]
This is because `db_connection(database.yml)` fails because `Error:  role "postgres" is not permitted to log in`.

**Comment by peterhurford** [comment]
It's important to `CREATE ROLE postgres; ALTER ROLE postgres WITH LOGIN;` in addition to the current steps suggested.  That solves the issue and this can be closed.  I don't know if you want to add that to the instructions or not.

**Comment by robertzk** [comment]
This should be covered in the README:

```
To run tests locally, you'll need the following:

A working PostgreSQL installation and a dedicated user account, "postgres".
A database called "travis" that user "postgres" can access.
```
